// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    aggregator
    (
        init => init
        upgrade => upgrade
        xo => aggregate
        getReferralIdCounter => referral_id_counter
        getReferralConfig => referral_config
        getStaticFee => static_fee
        addReferral => add_referral
        setReferralFee => set_referral_fee
        setReferralActive => set_referral_active
        setReferralOwner => set_referral_owner
        setStaticFee => set_static_fee
        claimReferralFees => claim_referral_fees
        claimAdminFees => claim_admin_fees
        getReferrerBalances => get_referrer_balances
        getReferrerTokens => get_referrer_tokens
        getAdminFees => get_admin_fees_view
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
